name: full-reset
on:
   workflow_dispatch:
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         -  name: checkout repo content
            uses: actions/checkout@v2 # checkout the repository content to github runner
         -  name: setup python
            uses: actions/setup-python@v2
            with:
               python-version: '3.11.4' # install the python version needed
               cache: 'pip' # caching pip dependencies
         -  name: install python packages
            run: |
               python -m pip install --upgrade pip
               pip install -r requirements.txt
         -  name: full reset
            env:
               MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
            run: |
               python -c 'import actions; actions.full_reset();'